name: "Feature request"
description: "Suggest an idea or enhancement"
title: "feat: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please provide as much context as you can.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
      placeholder: Describe the feature/change.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered?
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope / implementation notes
      description: If you have ideas about routes, schema, tests, docs, etc.
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Links, screenshots, or related issues.
    validations:
      required: false
