name: Auto-merge Release Please PRs

on:
  pull_request:
    types: [labeled, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    if: |
      contains(github.event.pull_request.labels.*.name, 'autorelease: pending') &&
      startsWith(github.event.pull_request.head.ref, 'release-please--')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        run: gh pr merge "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
