name: CI

on:
  push:
  pull_request:

jobs:
  test:
    uses: matt-riley/matt-riley-ci/.github/workflows/bun-ci.yml@7fd3aefaab1ae14d063930c85b2d629280c36620 # v2
    with:
      require-lockfile: true
      run-test: true
